<a href="https://colab.research.google.com/github/miller00315/estatistica_machine_learning/blob/master/Curso_estatistica_e_aprendizado_de_m%C3%A1quina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Amostragem aleatória simples

In [1]:
import pandas as pd
import random 
import numpy as np

In [2]:
dataset = pd.read_csv('census.csv')

In [3]:
dataset.shape

(32561, 15)

In [5]:
dataset.head() # Apresenta os cinco primeiros dados da base, par que possamos aprende a como separar os dados e prever a renda

age          workclass  final-weight  ... hour-per-week  native-country  income
0   39          State-gov         77516  ...            40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...            13   United-States   <=50K
2   38            Private        215646  ...            40   United-States   <=50K
3   53            Private        234721  ...            40   United-States   <=50K
4   28            Private        338409  ...            40            Cuba   <=50K

[5 rows x 15 columns]

In [6]:
dataset.tail() # Apresenta os últimos aquivos para que possamos avaliar os dados

age      workclass  final-weight  ... hour-per-week  native-country  income
32556   27        Private        257302  ...            38   United-States   <=50K
32557   40        Private        154374  ...            40   United-States    >50K
32558   58        Private        151910  ...            40   United-States   <=50K
32559   22        Private        201490  ...            20   United-States   <=50K
32560   52   Self-emp-inc        287927  ...            40   United-States    >50K

[5 rows x 15 columns]

In [9]:
df_simple_ramdom_sample = dataset.sample(n = 100, random_state=1) # n é a quantidade de elementos aleatórios que quero

In [8]:
df_simple_ramdom_sample.shape # verifica o tamanho da amostra e o formato

(100, 15)

In [10]:
def sampling_random_simple(dataset, samples): # retorna amostra aleatória simples
  return dataset.sample(n = samples, random_state=1) 

In [14]:
df_simple_ramdom_sample = sampling_random_simple(dataset, 100)
df_simple_ramdom_sample.shape # shape não é uma função, atenção
df_simple_ramdom_sample.head()

age          workclass  ...  native-country  income
9646    62   Self-emp-not-inc  ...   United-States   <=50K
709     18            Private  ...   United-States   <=50K
7385    25            Private  ...   United-States    >50K
16671   33            Private  ...   United-States   <=50K
21932   36            Private  ...   United-States   <=50K

[5 rows x 15 columns]

Amostragem sistemática

Você desenvolve um sistema para que os elementos sejam selecionados.

In [15]:
dataset.shape

(32561, 15)

In [19]:
chunks = len(dataset) // 100 # // arredonda o resultado
chunks

325

In [22]:
random.seed(1) #mantém os resultados padronizados
initial_number = random.randint(0, chunks)
initial_number

68

In [23]:
result = np.arange(initial_number, len(dataset), step=chunks)
result

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [26]:
def sistemic_sample(dataset, samples): #função que resume os processos acima
  interval = len(dataset) // samples # define o itervalo das amostras como a média aredondada do tamanho do dataset pela quantidade de amostras
  random.seed(1) # padroniza a seed para manter os testes coerentes
  start = random.randint(0, interval) # seleciona o primeiro item a utilizado
  indexes = np.arange(start, len(dataset), step = interval)  # utiliza a numpy para selecionar os índices de acordo com o intervalo
  sistemic_samples = dataset.iloc[indexes] # coleta dentro do dataset os items necessários
  return sistemic_samples # retorna o resultado

In [27]:
df_sistemic_sample = sistemic_sample(dataset, 100)
df_sistemic_sample.shape

(100, 15)

In [28]:
df_sistemic_sample.head()

age      workclass  final-weight  ... hour-per-week  native-country  income
68     49   Self-emp-inc        191681  ...            50   United-States    >50K
393    34      State-gov         98101  ...            45               ?    >50K
718    22        Private        214399  ...            15   United-States   <=50K
1043   44        Private        167005  ...            60   United-States    >50K
1368   52        Private        152234  ...            40           Japan    >50K

[5 rows x 15 columns]

Amostragem por grupos

Definimos grupos e não necessariamente as amostras a serem geradas, depois retornamos os elementos dentro destes grupos. Depois utilizamos a amostragem aleatória simples para selecionar os elementos a serem analizados.

In [29]:
chunk_size = len(dataset) / 10
chunk_size

3256.1

In [34]:
groups = []
group_id = 0
counter = 0

for _ in dataset.iterrows(): # iterrows percorre as linhas do dataset
  groups.append(group_id) # adiciono o id do grupo ao array de grupos
  counter += 1 # aumento o contador que verificará o fim da adicição de items
  if counter > 3256: #avalio se já cehgou ao fim do tamanho do grupo
    counter = 0 # retorno o contador a zero
    group_id += 1 # altero o id do grupo para a próxima etapa

In [40]:
np.unique(groups, return_counts=True) #verifique se a divisão de items ocorreu corretamente

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [41]:
np.shape(groups), dataset.shape #verifica se a divisão ocorreu corretamente

((32561,), (32561, 15))

In [42]:
dataset['group'] = groups # concateno a tabela 

In [43]:
dataset.head()

age          workclass  final-weight  ...  native-country  income group
0   39          State-gov         77516  ...   United-States   <=50K     0
1   50   Self-emp-not-inc         83311  ...   United-States   <=50K     0
2   38            Private        215646  ...   United-States   <=50K     0
3   53            Private        234721  ...   United-States   <=50K     0
4   28            Private        338409  ...            Cuba   <=50K     0

[5 rows x 16 columns]

In [50]:
random.seed(1) # padroniza o resultado
ramdom_group_id = random.randint(min(groups), max(groups))

In [51]:
df_agroupment = dataset[dataset['group'] == ramdom_group_id] # Seleciono um grupo baseado no id do grupo selecionado de forma aleatória
df_agroupment.shape

(3257, 16)

In [53]:
df_agroupment['group'].value_counts()

2    3257
Name: group, dtype: int64

In [62]:
def agroupment_sample(dataset, group_number):
  interval = len(dataset) // group_number # define o itervalo das amostras como a média aredondada do tamanho do dataset pela quantidade de amostras
  
  groups = []
  group_id = 0
  counter = 0

  for _ in dataset.iterrows(): # iterrows percorre as linhas do dataset
    groups.append(group_id) # adiciono o id do grupo ao array de grupos
    counter += 1 # aumento o contador que verificará o fim da adicição de items
    if counter > interval: #avalio se já chegou ao fim do tamanho do grupo
      counter = 0 # retorno o contador a zero
      group_id += 1 # altero o id do grupo para a próxima etapa

  dataset['group'] = groups # concateno a tabela
  random.seed(1) #padroniza o resultado
  selected_group = random.randint(0, group_number) #seleciona um número aleatór
  return dataset[dataset['group'] == selected_group] 

In [65]:
df_agrupment_sample = agroupment_sample(dataset, 325)

df_agrupment_sample.shape, df_agrupment_sample['group'].value_counts()

((101, 16), 68    101
 Name: group, dtype: int64)

In [66]:
df_agrupment_sample.head()

age workclass  final-weight  ...  native-country  income group
6868   32   Private        128016  ...   United-States   <=50K    68
6869   46   Private        360096  ...   United-States    >50K    68
6870   30   Private        170154  ...   United-States    >50K    68
6871   35   Private        337286  ...   United-States   <=50K    68
6872   52   Private        204322  ...   United-States   <=50K    68

[5 rows x 16 columns]

Amostragem estratificada

Primeiro estratifico os grupos, depois faço uma seleção nestes grupos, por exemplo uma seleção aleatória simples.

In [67]:
from sklearn.model_selection import StratifiedShuffleSplit # passa um campo e faz a divisão entre estratos

In [68]:
dataset['income'].value_counts() #verificamos a qunatidade de items para clacular a representividade

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [69]:
7841 / len(dataset), 24720 / len(dataset)

(0.2408095574460244, 0.7591904425539756)

In [70]:
split = StratifiedShuffleSplit(test_size=0.1) # função que define o tamanho da divisão, no caso 90 e 10

for x,y in split.split(dataset, dataset['income']): # loop responsável por percorrer os items de acordo com uma coluna específica e separar em dois campos
  df_x = dataset.iloc[x] # recebe os 90%
  df_y = dataset.iloc[y] # receb os 10%

df_x.shape, df_y.shape

((29304, 16), (3257, 16))

In [71]:
df_x.head()

age      workclass  final-weight  ...  native-country  income group
1666    50   Self-emp-inc        160151  ...   United-States    >50K    16
23761   47        Private         34458  ...   United-States   <=50K   235
27977   35        Private        197719  ...   United-States   <=50K   277
7670    35        Private        308945  ...   United-States   <=50K    75
23677   72        Private        497280  ...   United-States   <=50K   234

[5 rows x 16 columns]

In [72]:
100 / len(dataset)

0.0030711587481956942

In [73]:
split = StratifiedShuffleSplit(test_size=0.0030711587481956942) # função que define o tamanho da divisão, no caso queremos uma amostra com 100 items

for x,y in split.split(dataset, dataset['income']): # loop responsável por percorrer os items de acordo com uma coluna específica e separar em dois campos
  df_x = dataset.iloc[x] 
  df_y = dataset.iloc[y]

df_x.shape, df_y.shape

((32461, 16), (100, 16))

In [75]:
df_y['income'].value_counts()

 <=50K    76
 >50K     24
Name: income, dtype: int64

In [85]:
def stratified_sample(dataset, item_count, field):
  test_size = item_count / len(dataset)

  split = StratifiedShuffleSplit(test_size=test_size)

  for _,y in split.split(dataset, dataset[field]): # loop responsável por percorrer os items de acordo com uma coluna específica e separar em dois campos
    df_y = dataset.iloc[y]

  return df_y

res = stratified_sample(dataset, 100, 'income')

res['income'].value_counts()

 <=50K    76
 >50K     24
Name: income, dtype: int64

Amostra de reservatório

EVrifica itens de tamanho desconhecido que podem ser acessados somente uma vez e todos devem ter a mesma chance de serem acessados, por exemplo, compras pela internet.

In [83]:
def reservoir_sample(dataset, samples):
  stream = []

  for i in range(len(dataset)):
    stream.append(i)
  
  i = 0
  length = len(dataset)

  reservoir = [0] * samples

  for i in range(samples):
      reservoir[i] = stream[i]
  
  while i < length:
    j = random.randrange(i + 1)
    if j < samples:
      reservoir[j] = stream[i]
    i += 1

  return dataset.iloc[reservoir]


In [84]:
df_reservoir_samples = reservoir_sample(dataset, 100)

df_reservoir_samples.shape

(100, 16)