<a href="https://colab.research.google.com/github/miller00315/estatistica_machine_learning/blob/master/distribuicao_binomial_poisson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Binomial sucesso ou falha*

In [49]:
import pandas as pd
import seaborn as sns
import math
from scipy import stats
import numpy as np

In [4]:
x = 5 # número de sucessos
p = 0.5 #probabilidade de sucesso
n = 10 #quantidade de tentativas - trials

In [7]:
(math.factorial(n) / (math.factorial(n - x) * math.factorial(x))) * math.pow(p, x) * math.pow(1 - p, n - x)

0.24609375

In [10]:
stats.binom.pmf(x,n,p)

0.24609375000000025

In [14]:
x = 7 # número de sucessos
p = 0.7 #probabilidade de sucesso
n = 10 #quantidade de tentativas - trials

In [15]:
(math.factorial(n) / (math.factorial(n - x) * math.factorial(x))) * math.pow(p, x) * math.pow(1 - p, n - x)

0.266827932

In [17]:
stats.binom.pmf(x,n,p)

0.26682793200000016

In [18]:
x = 1 # número de sucessos
p = 0.05 #probabilidade de sucesso
n = 50 #quantidade de tentativas - trials

In [19]:
stats.binom.pmf(x,n,p)

0.20248677704398393

In [20]:
x = 0 # número de sucessos
p = 0.05 #probabilidade de sucesso
n = 50 #quantidade de tentativas - trials

In [21]:
stats.binom.pmf(x,n,p)

0.0769449752767133

Poisson sucesso ou falha em um espaço temporal

In [22]:
euler_number = 2.71828

In [32]:
x = 8 # quantidade de eventos
media = 10 #media no tempo
math.e # numero de euler

2.718281828459045

In [34]:
math.pow(math.e, -media) * (math.pow(media, x) / math.factorial(x))

0.11259903214902002

In [33]:
stats.poisson.pmf(x, media)

0.11259903214902009

In [39]:
x = 1 # quantidade de eventos
media = 0.05 #media no tempo

stats.poisson.pmf(x, media)

0.04756147122503571

In [37]:
x = 5 # quantidade de eventos
media = 50 #media no tempo

In [38]:
stats.poisson.pmf(x, media)

5.02278606240605e-16

In [40]:
dataset = pd.read_csv('credit_data.csv')
dataset.dropna(inplace=True) # excluir fatores faltantes
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [41]:
X = dataset.iloc[:,1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [42]:
y = dataset.iloc[:,4].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [43]:
from sklearn.naive_bayes import GaussianNB
naive_bayes = GaussianNB()
naive_bayes.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [44]:
X[0], X[0].shape

(array([6.61559251e+04, 5.90170151e+01, 8.10653213e+03]), (3,))

In [45]:
novo = X[0].reshape(1,-1)
novo.shape

(1, 3)

In [46]:
naive_bayes.predict(novo)

array([0])

In [47]:
previsao = naive_bayes.predict_proba(novo) # previsão e probabilidade
previsao

array([[1.00000000e+00, 2.03924534e-10]])

In [50]:
np.argmax(previsao) # classe com o maior valor

0